version: '3'
services:

  p4v_env:
    build: .
    image: p4v_env-image
    container_name: p4v_env01
    volumes:
      - .:/home/share
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /bin/fish
    environment:
      - DISPLAY=192.168.0.130:0.0
    tty: true
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
      - SYS_NICE 
    cpu_rt_runtime: 950000
